server:
  port: ${CONFIG_SERVER_PORT:8888}
  
spring:
  application:
    name: config
  profiles:
    active: development  

--- 
spring:
  profiles: development
  cloud:
    config:
      server:
        git:
          uri: https://github.com/inlineno1/test-repo.git

---
spring:
  profiles: vm
  cloud:
    config:
      server:
        git:
          uri: https://github.com/inlineno1/test-repo.git 
